### ISSUE TITLE
Add code coverage analysis from Codecov

### ISSUE THREAD

**Issue by gsheni** [trane-dev/Trane#70]
```
     - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ${{ github.workspace }}/coverage.xml
          verbose: true
```
